# Generated by Django 5.0.6 on 2024-08-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("index", "0013_rename_gorod_opisanie_bbb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("data", models.DateField()),
                ("time", models.TimeField()),
                ("name", models.CharField(max_length=150)),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erer",
                        to="index.names",
                    ),
                ),
            ],
        ),
    ]
