# Generated by Django 5.0.6 on 2024-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zakazy", "0002_rename_data_bron_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sucsesful",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=4)),
            ],
        ),
    ]
