# Generated by Django 5.0.6 on 2024-08-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zakazy", "0003_sucsesful"),
    ]

    operations = [
        migrations.AddField(
            model_name="bron",
            name="sostoinie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sostoinie",
                to="zakazy.sucsesful",
            ),
        ),
    ]
