# Generated by Django 5.0.6 on 2024-08-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zakazy", "0004_bron_sostoinie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bron",
            name="sostoinie",
            field=models.ForeignKey(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sostoinie",
                to="zakazy.sucsesful",
            ),
        ),
    ]
