# Generated by Django 5.0.6 on 2024-08-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otzv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.CharField(max_length=400)),
                (
                    "hotel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="index.hotel",
                    ),
                ),
            ],
        ),
    ]
