# Generated by Django 5.0.6 on 2024-08-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocenki", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mnenie",
            name="name",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
