# Generated by Django 5.0.6 on 2024-08-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotelopisanie",
            old_name="name",
            new_name="title",
        ),
    ]
