# Generated by Django 5.0.6 on 2024-08-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_musician_remove_hotelopisanie_title_album_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Names",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("adress", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Opisanie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placesbeside", models.CharField(max_length=200)),
                ("character", models.CharField(max_length=200)),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opisanie",
                        to="index.names",
                    ),
                ),
            ],
        ),
    ]
