# Generated by Django 5.0.6 on 2024-08-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0007_remove_city_adress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Musician",
        ),
    ]
