# Generated by Django 5.0.6 on 2024-08-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0009_alter_opisanie_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opisanie",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opisanie",
                to="index.names",
            ),
        ),
    ]
