# Generated by Django 5.0.6 on 2024-08-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0010_alter_opisanie_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="opisanie",
            name="address",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opisanie",
            name="house",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opisanie",
            name="stroenie",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
