# Generated by Django 5.0.6 on 2024-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0011_opisanie_address_opisanie_house_opisanie_stroenie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opisanie",
            name="stroenie",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
