# Generated by Django 5.0.6 on 2024-08-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0012_alter_opisanie_stroenie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opisanie",
            old_name="gorod",
            new_name="bbb",
        ),
    ]
