# Generated by Django 5.0.6 on 2024-08-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0014_mnenie"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mnenie",
        ),
    ]
